/**
 * Generated by Apache Flex Cross-Compiler from BindableWithConstructorInitEnum.as
 * BindableWithConstructorInitEnum
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('BindableWithConstructorInitEnum');

goog.require('org.apache.flex.events.EventDispatcher');



/**
 * @constructor
 * @extends {org.apache.flex.events.EventDispatcher}
 * @param {string} value
 * @param {number} ordinal
 */
BindableWithConstructorInitEnum = function(value, ordinal) {
  BindableWithConstructorInitEnum.base(this, 'constructor');
  this.value = value;
  this.ordinal = ordinal;
};
goog.inherits(BindableWithConstructorInitEnum, org.apache.flex.events.EventDispatcher);


/**
 * @export
 * @const
 * @type {BindableWithConstructorInitEnum}
 */
BindableWithConstructorInitEnum.STATIC_INIT_ = new BindableWithConstructorInitEnum("STATIC_INIT", -1);


/**
 * @export
 * @type {number}
 */
BindableWithConstructorInitEnum.prototype.ordinal_;


/**
 * @export
 * @type {string}
 */
BindableWithConstructorInitEnum.prototype.value_;Object.defineProperties(BindableWithConstructorInitEnum.prototype, /** @lends {BindableWithConstructorInitEnum.prototype} */ {
/** @export */
STATIC_INIT: {
/** @this {BindableWithConstructorInitEnum} */
  get: function() {
  return this.STATIC_INIT_;
  },

/** @this {BindableWithConstructorInitEnum} */
set: function(value) {
if (value != this.STATIC_INIT_) {
    var oldValue = this.STATIC_INIT_;
    this.STATIC_INIT_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "STATIC_INIT", oldValue, value));
}
}},/** @export */
ordinal: {
/** @this {BindableWithConstructorInitEnum} */
  get: function() {
  return this.ordinal_;
  },

/** @this {BindableWithConstructorInitEnum} */
set: function(value) {
if (value != this.ordinal_) {
    var oldValue = this.ordinal_;
    this.ordinal_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "ordinal", oldValue, value));
}
}},/** @export */
value: {
/** @this {BindableWithConstructorInitEnum} */
  get: function() {
  return this.value_;
  },

/** @this {BindableWithConstructorInitEnum} */
set: function(value) {
if (value != this.value_) {
    var oldValue = this.value_;
    this.value_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "value", oldValue, value));
}
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
BindableWithConstructorInitEnum.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'BindableWithConstructorInitEnum', qName: 'BindableWithConstructorInitEnum'}] };


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('BindableWithConstructorInitEnum', BindableWithConstructorInitEnum);



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
BindableWithConstructorInitEnum.prototype.FLEXJS_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'ordinal': { type: 'int'},
        'value': { type: 'String'}
      };
    },
    accessors: function () {
      return {
      };
    },
    methods: function () {
      return {
        'BindableWithConstructorInitEnum': { type: '', declaredBy: 'BindableWithConstructorInitEnum'}
      };
    },
    metadata: function () { return [ ]; }
  };
};
